Listen 8080

<VirtualHost *:8080>
    ServerName localhost
    DocumentRoot /app
    DirectoryIndex Default.aspx
    RewriteEngine On
    RewriteRule ^$ /Default.aspx [R=302,L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI}.aspx -f
    RewriteRule ^(.+?)/?$ /$1.aspx [R=302,L,NE]

    MonoServerPath ametvps "/usr/bin/mod-mono-server4"
    MonoApplications ametvps "/:/app"

    <Location />
        SetHandler mono
        MonoSetServerAlias ametvps
    </Location>

    <Directory /app>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>
